export const LANGUAGES = {
  python: {
    label: 'Python',
    monacoId: 'python',
    glossary: {
      'def': { definition: 'Defines a function in Python.', example: 'def greet(name):\n    print(f"Hello {name}")' },
      'class': { definition: 'Defines a class — a blueprint for creating objects.', example: 'class Dog:\n    def __init__(self, name):\n        self.name = name' },
      'if': { definition: 'Starts a conditional block. Executes code only if the condition is True.', example: 'if x > 10:\n    print("big number")' },
      'elif': { definition: 'Short for "else if". Checks another condition if the previous one was False.', example: 'if x > 10:\n    print("big")\nelif x > 5:\n    print("medium")' },
      'else': { definition: 'Runs if all previous if/elif conditions were False.', example: 'if x > 0:\n    print("positive")\nelse:\n    print("not positive")' },
      'for': { definition: 'Loops over items in a sequence (list, range, string, etc.).', example: 'for i in range(5):\n    print(i)' },
      'while': { definition: 'Repeats a block as long as the condition remains True.', example: 'while count > 0:\n    count -= 1' },
      'return': { definition: 'Sends a value back from a function to the caller.', example: 'def add(a, b):\n    return a + b' },
      'import': { definition: 'Brings in a module or specific names from a module.', example: 'import os\nfrom math import sqrt' },
      'from': { definition: 'Used with import to bring in specific items from a module.', example: 'from datetime import datetime' },
      'try': { definition: 'Starts an error-handling block. Code inside may raise exceptions.', example: 'try:\n    result = 10 / x\nexcept ZeroDivisionError:\n    print("Cannot divide by zero")' },
      'except': { definition: 'Catches and handles a specific exception from a try block.', example: 'except ValueError as e:\n    print(f"Invalid value: {e}")' },
      'with': { definition: 'Context manager — automatically handles setup and cleanup (e.g., closing files).', example: 'with open("file.txt") as f:\n    data = f.read()' },
      'lambda': { definition: 'Creates a small anonymous (unnamed) function in one line.', example: 'square = lambda x: x ** 2\nprint(square(5))  # 25' },
      'in': { definition: 'Checks membership or iterates through a sequence.', example: 'if "a" in "apple":\n    print("found it")' },
      'True': { definition: 'Boolean value representing truth.', example: 'is_active = True' },
      'False': { definition: 'Boolean value representing falsehood.', example: 'is_done = False' },
      'None': { definition: 'Represents the absence of a value (like null in other languages).', example: 'result = None' },
      'print': { definition: 'Built-in function that outputs text to the console.', example: 'print("Hello, world!")' },
      'range': { definition: 'Generates a sequence of numbers. Often used in for loops.', example: 'for i in range(0, 10, 2):\n    print(i)  # 0, 2, 4, 6, 8' },
    },
  },
  javascript: {
    label: 'JavaScript',
    monacoId: 'javascript',
    glossary: {
      'const': { definition: 'Declares a constant variable that cannot be reassigned.', example: 'const name = "Alice";' },
      'let': { definition: 'Declares a block-scoped variable that can be reassigned.', example: 'let count = 0;\ncount = count + 1;' },
      'var': { definition: 'Declares a function-scoped variable. Prefer const/let in modern JS.', example: 'var x = 10;' },
      'function': { definition: 'Declares a named function.', example: 'function greet(name) {\n  return `Hello ${name}`;\n}' },
      'if': { definition: 'Conditional statement. Executes a block if the condition is true.', example: 'if (x > 10) {\n  console.log("big");\n}' },
      'else': { definition: 'Executes when the if condition is false.', example: 'if (x > 0) {\n  console.log("positive");\n} else {\n  console.log("non-positive");\n}' },
      'for': { definition: 'Loop that repeats code a set number of times.', example: 'for (let i = 0; i < 10; i++) {\n  console.log(i);\n}' },
      'while': { definition: 'Loop that repeats while a condition is true.', example: 'while (count > 0) {\n  count--;\n}' },
      'return': { definition: 'Returns a value from a function.', example: 'function add(a, b) {\n  return a + b;\n}' },
      'class': { definition: 'Defines a class (ES6+) — a template for objects.', example: 'class Animal {\n  constructor(name) {\n    this.name = name;\n  }\n}' },
      'import': { definition: 'Imports bindings from another module (ES6 modules).', example: 'import { readFile } from "fs";' },
      'export': { definition: 'Exports functions, objects, or values from a module.', example: 'export function greet() { }' },
      'async': { definition: 'Declares an asynchronous function that returns a Promise.', example: 'async function fetchData() {\n  const res = await fetch(url);\n  return res.json();\n}' },
      'await': { definition: 'Pauses async function execution until a Promise resolves.', example: 'const data = await fetch(url);' },
      'try': { definition: 'Starts an error-handling block.', example: 'try {\n  JSON.parse(input);\n} catch (e) {\n  console.error("Invalid JSON");\n}' },
      'catch': { definition: 'Handles errors thrown in the try block.', example: 'catch (error) {\n  console.error(error.message);\n}' },
      'console.log': { definition: 'Prints output to the developer console.', example: 'console.log("Hello, world!");' },
      '=>': { definition: 'Arrow function syntax — shorthand for function expressions.', example: 'const add = (a, b) => a + b;' },
    },
  },
  java: {
    label: 'Java',
    monacoId: 'java',
    glossary: {
      'public': { definition: 'Access modifier — the member is accessible from any other class.', example: 'public class Main { }' },
      'private': { definition: 'Access modifier — the member is only accessible within its own class.', example: 'private int count = 0;' },
      'class': { definition: 'Defines a class — the fundamental building block of Java programs.', example: 'public class Animal {\n    String name;\n}' },
      'static': { definition: 'Belongs to the class itself, not to instances. Can be called without creating an object.', example: 'public static void main(String[] args) { }' },
      'void': { definition: 'Indicates a method does not return a value.', example: 'public void printHello() {\n    System.out.println("Hello");\n}' },
      'if': { definition: 'Conditional statement that executes code when the condition is true.', example: 'if (x > 10) {\n    System.out.println("big");\n}' },
      'else': { definition: 'Executes when the if condition is false.', example: 'else {\n    System.out.println("small");\n}' },
      'for': { definition: 'Loop that repeats with a counter variable.', example: 'for (int i = 0; i < 10; i++) {\n    System.out.println(i);\n}' },
      'while': { definition: 'Loop that repeats while a condition is true.', example: 'while (count > 0) {\n    count--;\n}' },
      'return': { definition: 'Returns a value from a method.', example: 'public int add(int a, int b) {\n    return a + b;\n}' },
      'new': { definition: 'Creates a new instance (object) of a class.', example: 'Dog myDog = new Dog("Rex");' },
      'import': { definition: 'Imports a class or package for use in the current file.', example: 'import java.util.ArrayList;' },
      'try': { definition: 'Starts an error-handling block for code that may throw exceptions.', example: 'try {\n    int result = 10 / x;\n} catch (Exception e) {\n    e.printStackTrace();\n}' },
      'catch': { definition: 'Catches and handles an exception from a try block.', example: 'catch (IOException e) {\n    System.err.println(e.getMessage());\n}' },
      'extends': { definition: 'Makes a class inherit from another class.', example: 'class Dog extends Animal { }' },
      'implements': { definition: 'Makes a class implement an interface.', example: 'class MyList implements List<String> { }' },
      'String': { definition: 'Built-in class representing a sequence of characters (text).', example: 'String name = "Alice";' },
      'int': { definition: 'Primitive type for whole numbers (32-bit integer).', example: 'int count = 42;' },
      'System.out.println': { definition: 'Prints a line of text to the console.', example: 'System.out.println("Hello!");' },
    },
  },
  cpp: {
    label: 'C++',
    monacoId: 'cpp',
    glossary: {
      '#include': { definition: 'Preprocessor directive that includes a header file.', example: '#include <iostream>\n#include <string>' },
      'using': { definition: 'Brings names from a namespace into scope.', example: 'using namespace std;' },
      'int': { definition: 'Integer type — stores whole numbers.', example: 'int x = 42;' },
      'void': { definition: 'Indicates a function returns no value.', example: 'void printHello() {\n    cout << "Hello" << endl;\n}' },
      'class': { definition: 'Defines a class with members and methods.', example: 'class Dog {\npublic:\n    string name;\n};' },
      'if': { definition: 'Conditional statement.', example: 'if (x > 10) {\n    cout << "big" << endl;\n}' },
      'else': { definition: 'Executes when the if condition is false.', example: 'else {\n    cout << "small" << endl;\n}' },
      'for': { definition: 'Loop with counter.', example: 'for (int i = 0; i < 10; i++) {\n    cout << i << endl;\n}' },
      'while': { definition: 'Loop that repeats while condition is true.', example: 'while (count > 0) {\n    count--;\n}' },
      'return': { definition: 'Returns a value from a function.', example: 'int add(int a, int b) {\n    return a + b;\n}' },
      'cout': { definition: 'Standard output stream — used to print to console.', example: 'cout << "Hello, world!" << endl;' },
      'cin': { definition: 'Standard input stream — reads user input from console.', example: 'cin >> name;' },
      'std': { definition: 'The standard namespace containing built-in C++ library features.', example: 'std::cout << "Hello";' },
      'auto': { definition: 'Lets the compiler deduce the type automatically.', example: 'auto x = 3.14;  // deduced as double' },
      'new': { definition: 'Allocates memory on the heap and returns a pointer.', example: 'int* ptr = new int(42);' },
      'nullptr': { definition: 'Null pointer literal (C++11+). Represents a pointer that points to nothing.', example: 'int* ptr = nullptr;' },
      'struct': { definition: 'Defines a structure — like a class but members are public by default.', example: 'struct Point {\n    int x;\n    int y;\n};' },
      'template': { definition: 'Creates generic functions or classes that work with any type.', example: 'template <typename T>\nT max(T a, T b) {\n    return (a > b) ? a : b;\n}' },
    },
  },
  csharp: {
    label: 'C#',
    monacoId: 'csharp',
    glossary: {
      'using': { definition: 'Imports a namespace or ensures an object is disposed after use.', example: 'using System;\nusing System.Collections.Generic;' },
      'class': { definition: 'Defines a class — the core building block of C# programs.', example: 'public class Person {\n    public string Name { get; set; }\n}' },
      'public': { definition: 'Access modifier — accessible from any code.', example: 'public void Greet() { }' },
      'private': { definition: 'Access modifier — accessible only within the same class.', example: 'private int _count;' },
      'static': { definition: 'Belongs to the type itself rather than a specific instance.', example: 'public static void Main(string[] args) { }' },
      'void': { definition: 'Indicates a method returns no value.', example: 'public void PrintHello() {\n    Console.WriteLine("Hello");\n}' },
      'if': { definition: 'Conditional statement.', example: 'if (x > 10) {\n    Console.WriteLine("big");\n}' },
      'else': { definition: 'Executes when the if condition is false.', example: 'else {\n    Console.WriteLine("small");\n}' },
      'for': { definition: 'Loop with a counter variable.', example: 'for (int i = 0; i < 10; i++) {\n    Console.WriteLine(i);\n}' },
      'foreach': { definition: 'Iterates over each element in a collection.', example: 'foreach (var item in list) {\n    Console.WriteLine(item);\n}' },
      'while': { definition: 'Loop that repeats while a condition is true.', example: 'while (count > 0) {\n    count--;\n}' },
      'return': { definition: 'Returns a value from a method.', example: 'public int Add(int a, int b) {\n    return a + b;\n}' },
      'var': { definition: 'Implicitly typed local variable — compiler infers the type.', example: 'var name = "Alice";  // inferred as string' },
      'new': { definition: 'Creates a new instance of a class.', example: 'var dog = new Dog("Rex");' },
      'string': { definition: 'Built-in type for text.', example: 'string greeting = "Hello!";' },
      'int': { definition: 'Built-in type for 32-bit integers.', example: 'int count = 42;' },
      'async': { definition: 'Marks a method as asynchronous.', example: 'public async Task<string> FetchDataAsync() { }' },
      'await': { definition: 'Waits for an async operation to complete.', example: 'var data = await httpClient.GetStringAsync(url);' },
      'Console.WriteLine': { definition: 'Prints a line of text to the console.', example: 'Console.WriteLine("Hello, world!");' },
    },
  },
  go: {
    label: 'Go',
    monacoId: 'go',
    glossary: {
      'package': { definition: 'Declares which package this file belongs to.', example: 'package main' },
      'import': { definition: 'Imports packages for use.', example: 'import (\n    "fmt"\n    "os"\n)' },
      'func': { definition: 'Declares a function.', example: 'func greet(name string) string {\n    return "Hello " + name\n}' },
      'if': { definition: 'Conditional statement.', example: 'if x > 10 {\n    fmt.Println("big")\n}' },
      'else': { definition: 'Executes when the if condition is false.', example: 'else {\n    fmt.Println("small")\n}' },
      'for': { definition: 'The only loop construct in Go — replaces while, for, and foreach.', example: 'for i := 0; i < 10; i++ {\n    fmt.Println(i)\n}' },
      'range': { definition: 'Iterates over elements of arrays, slices, maps, strings, or channels.', example: 'for i, v := range items {\n    fmt.Println(i, v)\n}' },
      'return': { definition: 'Returns values from a function. Go supports multiple return values.', example: 'func divide(a, b float64) (float64, error) {\n    if b == 0 {\n        return 0, errors.New("divide by zero")\n    }\n    return a / b, nil\n}' },
      'struct': { definition: 'Defines a composite type — a collection of fields.', example: 'type Person struct {\n    Name string\n    Age  int\n}' },
      'type': { definition: 'Declares a new named type.', example: 'type ID int' },
      'var': { definition: 'Declares a variable with an explicit type.', example: 'var count int = 0' },
      ':=': { definition: 'Short variable declaration — declares and assigns with inferred type.', example: 'name := "Alice"' },
      'interface': { definition: 'Defines a set of method signatures. Types implement interfaces implicitly.', example: 'type Reader interface {\n    Read(p []byte) (n int, err error)\n}' },
      'go': { definition: 'Starts a goroutine — a lightweight concurrent thread.', example: 'go processData(data)' },
      'chan': { definition: 'Channel type — used for communication between goroutines.', example: 'ch := make(chan int)' },
      'defer': { definition: 'Schedules a function call to run when the surrounding function returns.', example: 'defer file.Close()' },
      'nil': { definition: 'Zero value for pointers, interfaces, maps, slices, channels, and functions.', example: 'if err != nil {\n    log.Fatal(err)\n}' },
      'fmt.Println': { definition: 'Prints values to standard output followed by a newline.', example: 'fmt.Println("Hello, world!")' },
    },
  },
  rust: {
    label: 'Rust',
    monacoId: 'rust',
    glossary: {
      'fn': { definition: 'Declares a function.', example: 'fn greet(name: &str) -> String {\n    format!("Hello {}", name)\n}' },
      'let': { definition: 'Declares an immutable variable binding.', example: 'let x = 42;' },
      'let mut': { definition: 'Declares a mutable variable binding.', example: 'let mut count = 0;\ncount += 1;' },
      'if': { definition: 'Conditional expression.', example: 'if x > 10 {\n    println!("big");\n}' },
      'else': { definition: 'Executes when the if condition is false.', example: 'else {\n    println!("small");\n}' },
      'for': { definition: 'Iterates over an iterator.', example: 'for i in 0..10 {\n    println!("{}", i);\n}' },
      'loop': { definition: 'Infinite loop — must use break to exit.', example: 'loop {\n    if done { break; }\n}' },
      'while': { definition: 'Loop that repeats while condition is true.', example: 'while count > 0 {\n    count -= 1;\n}' },
      'match': { definition: 'Pattern matching — like a powerful switch statement.', example: 'match value {\n    1 => println!("one"),\n    2 => println!("two"),\n    _ => println!("other"),\n}' },
      'struct': { definition: 'Defines a structure with named fields.', example: 'struct Point {\n    x: f64,\n    y: f64,\n}' },
      'impl': { definition: 'Implements methods for a struct or trait.', example: 'impl Point {\n    fn new(x: f64, y: f64) -> Self {\n        Point { x, y }\n    }\n}' },
      'enum': { definition: 'Defines a type that can be one of several variants.', example: 'enum Color {\n    Red,\n    Green,\n    Blue,\n}' },
      'trait': { definition: 'Defines shared behavior (like interfaces in other languages).', example: 'trait Greet {\n    fn hello(&self) -> String;\n}' },
      'use': { definition: 'Brings items from a module into scope.', example: 'use std::collections::HashMap;' },
      'pub': { definition: 'Makes an item public (visible outside its module).', example: 'pub fn process(data: &str) { }' },
      'return': { definition: 'Returns a value from a function. Note: the last expression without ; is also returned.', example: 'fn add(a: i32, b: i32) -> i32 {\n    a + b  // implicit return\n}' },
      'println!': { definition: 'Macro that prints formatted text to stdout with a newline.', example: 'println!("Hello, {}!", name);' },
      'Option': { definition: 'Enum representing an optional value: Some(value) or None.', example: 'let result: Option<i32> = Some(42);' },
      'Result': { definition: 'Enum for operations that can fail: Ok(value) or Err(error).', example: 'fn parse(s: &str) -> Result<i32, ParseIntError> {\n    s.parse()\n}' },
    },
  },
  typescript: {
    label: 'TypeScript',
    monacoId: 'typescript',
    glossary: {
      'const': { definition: 'Declares a constant that cannot be reassigned.', example: 'const name: string = "Alice";' },
      'let': { definition: 'Declares a block-scoped variable.', example: 'let count: number = 0;' },
      'function': { definition: 'Declares a function with optional type annotations.', example: 'function add(a: number, b: number): number {\n  return a + b;\n}' },
      'interface': { definition: 'Defines the shape of an object — what properties and types it must have.', example: 'interface User {\n  name: string;\n  age: number;\n}' },
      'type': { definition: 'Creates a type alias — a name for any type.', example: 'type ID = string | number;' },
      'class': { definition: 'Defines a class with typed properties and methods.', example: 'class Animal {\n  constructor(public name: string) {}\n}' },
      'if': { definition: 'Conditional statement.', example: 'if (x > 10) {\n  console.log("big");\n}' },
      'else': { definition: 'Executes when the if condition is false.', example: 'else {\n  console.log("small");\n}' },
      'for': { definition: 'Loop with counter.', example: 'for (let i = 0; i < 10; i++) {\n  console.log(i);\n}' },
      'while': { definition: 'Loop while condition is true.', example: 'while (count > 0) {\n  count--;\n}' },
      'return': { definition: 'Returns a value from a function.', example: 'function add(a: number, b: number): number {\n  return a + b;\n}' },
      'import': { definition: 'Imports bindings from a module.', example: 'import { Component } from "react";' },
      'export': { definition: 'Exports declarations from a module.', example: 'export interface Config {\n  port: number;\n}' },
      'async': { definition: 'Declares an async function returning a Promise.', example: 'async function fetchData(): Promise<Data> { }' },
      'await': { definition: 'Waits for a Promise to resolve.', example: 'const data = await fetchData();' },
      'enum': { definition: 'Defines a set of named constants.', example: 'enum Direction {\n  Up,\n  Down,\n  Left,\n  Right,\n}' },
      'string': { definition: 'Type for text values.', example: 'const name: string = "Alice";' },
      'number': { definition: 'Type for numeric values (integers and floats).', example: 'const age: number = 30;' },
      'boolean': { definition: 'Type for true/false values.', example: 'const isActive: boolean = true;' },
      'console.log': { definition: 'Prints output to the console.', example: 'console.log("Hello, world!");' },
    },
  },
};

export const LANGUAGE_LIST = Object.entries(LANGUAGES).map(([id, lang]) => ({
  id,
  ...lang,
}));
